# version: "3.8"

services:
  redis-llm:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME:-redis-llm}
    ports:
      - "${REDIS_PORT:-6379}:6379" # 使用默认的主机端口6379，如果HOST_PORT有定义会覆盖默认
    volumes:
      - ../redis:/data # 持久化数据到主机的./redis目录 (Make the data persistent on the host)
      - ./redis.conf:/etc/redis/redis.conf # 挂载自定义的redis.conf配置文件
    command: [ "redis-server", "/etc/redis/redis.conf" ] # 启动redis，使用挂载的配置文件